In [1]:
import numpy as np

In [2]:
numeros = [1,2,3,4,5]

In [3]:
array = np.array(numeros)

In [4]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [14]:
np.random.randint(0,100)

81

In [15]:
array = np.random.randint(0,100,10)

In [16]:
array

array([74, 48, 84, 72, 86, 97, 15, 67, 89, 12])

In [17]:
array.max()

97

In [18]:
array.argmax()

5

In [19]:
array.min()

12

In [20]:
array.mean()

64.4

In [21]:
array.reshape(5,2)

array([[74, 48],
       [84, 72],
       [86, 97],
       [15, 67],
       [89, 12]])

In [22]:
array

array([74, 48, 84, 72, 86, 97, 15, 67, 89, 12])

In [23]:
array = array.reshape(5,2)

In [24]:
array

array([[74, 48],
       [84, 72],
       [86, 97],
       [15, 67],
       [89, 12]])

In [25]:
array[2,0]

86

In [26]:
filtro = array > 30
array2 = array[filtro]

In [27]:
array2

array([74, 48, 84, 72, 86, 97, 67, 89])